### ISSUE TITLE
Breaks other shortcode

### ISSUE THREAD

**Issue by tjbp** [billerickson/display-posts-shortcode#102]
I have this odd problem in which enabling this plugin causes NGG's ngg_images shortcode to not parse (example: http://sars.club/). Disabling the display-posts-shortcode causes NGG's shortcode to parse. After fishing through the code here I really can't see how this could be caused by your plugin, but perhaps you've come across this problem before?

**Comment by billerickson** [comment]
I'm sorry but no, I don't have any experience with that plugin or why it wouldn't work with Display Posts Shortcode. I know it sounds like passing the buck, but I recommend contacting NGG support and seeing if they can provide some guidance.

**Comment by tjbp** [comment]
No problem, really was just keen to see if you'd come across it before - I'll dig around more and probably return with a pull request if it relates to this at all.

**Comment by tjbp** [comment]
Just in case people find this through search engines:

NGG has a problem with other plugins that use the 'the_content' hook. Define the following constant somewhere in your wp-config, and NGG will behave.

```php
define('NGG_DISABLE_FILTER_THE_CONTENT', true);
```
