### ISSUE TITLE
Wrap date elements in selectors

### ISSUE THREAD

**Issue by dillonlara115** [billerickson/display-posts-shortcode#104]
Hi,

I was wondering if there was a way to wrap date items in separate dom wrappers.  For example, I'm using the shortcode and outputting the date as "M d" to show the month abbreviation and date(JAN 03).  however, I would like to style the month differently than the day and need some way to differentiate between the 2.  Currently they get wrapped in one span element but I need each date parameter inside that span to have a separate class/element to target and style with css.  Attached is what I'm trying to achieve.

Thanks,
![screen shot 2016-04-07 at 10 18 18 am](https://cloud.githubusercontent.com/assets/986385/14356340/1561c580-fcaa-11e5-8a62-e092dda13504.png)

**Comment by billerickson** [comment]
The reason I didn't wrap them in separate elements is the shortcode allows you to specify the date format, so I can't predict what date/time elements will be included and in what order.

I recommend you use the [output filter](https://github.com/billerickson/display-posts-shortcode/blob/master/display-posts-shortcode.php#L465) to modify the date that's output by the shortcode.
