### ISSUE TITLE
Add excerpt_length parameter

### ISSUE THREAD

**Issue by billerickson** [billerickson/display-posts-shortcode#106]
See #105 for the original pull request.

**Comment by KTS915** [comment]
Unfortunately, the latest version now apparently provides no way to display custom excerpts, and instead insists on taking the first n words from the post.

**Comment by KTS915** [comment]
Thank you. That was quick!

**Comment by billerickson** [comment]
Sorry, I should have thought about manual excerpts when I implemented that feature. 

My first thought was that get_the_excerpt() is limited to 55 words, so if you specify an excerpt_length longer than that you won't get a longer excerpt. That's why I used the full post content. 

Now the shortcode can be used for defining excerpts shorter than 55 words, but if you want one longer than 55 words you'll need to use the `excerpt_length` WordPress filter to extend the WP excerpt.

**Comment by KTS915** [comment]
This all seems like a great enhancement to me. 

Unfortunately, it seems that the manual excerpt function is not working on custom post types. (It is working fine on regular posts.)

**Comment by billerickson** [comment]
I am not having any issues using this with a custom post type.

1. I registered a 'testimonial' custom post type([code](https://gist.github.com/billerickson/e41617031879596d4f0d9995e882b31d)). I included 'excerpt' to the supports array
2. I created two testimonial posts. One with just title and content. One with title, content, and manual excerpt.
3. On a page I added [display-posts include_excerpt="true" post_type="testimonial"]. Both the manual and automatic excerpt displayed properly.

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/2p3k461u2H2k163g462l/Screen%20Shot%202016-05-20%20at%209.53.22%20AM.png?v=26f6c5a1)

**Comment by KTS915** [comment]
Thanks for this. I've done a lot more testing, and I agree that the problem is not caused by the excerpt being of a custom post type. 

In fact, the problem manifests itself when the manual excerpt is over 55 words long, irrespective of the post type.

**Comment by billerickson** [comment]
The shortcode truncates the excerpt to 55 words. That's the purpose of this recent change.

If you want to display manual excerpts that are longer than 55 words, do [display-posts excerpt_length="999"]. 

WordPress itself truncates the automatically generated excerpts to 55 words. If you wanted to extend the length of the automatic excerpts you would need to use both the [excerpt_length filter](https://codex.wordpress.org/Plugin_API/Filter_Reference/excerpt_length) to extend them in WordPress, and the 'excerpt_length' parameter in the shortcode.

**Comment by KTS915** [comment]
I see; I thought that the truncation applied only to non-manual excerpts. Thanks for the explanation!
