### ISSUE TITLE
add title to post thumbnail links

### ISSUE THREAD

**Issue by Jon007** [billerickson/display-posts-shortcode#109]
may I suggest adding title tag to thumbnail images to provide a mouseover tooltip, 
eg change line 402 to:
$image = '<a class="image" title="' . get_the_title() . '" href="' . get_permalink() . '">' . get_the_post_thumbnail( get_the_ID(), $image_size ) . '</a> ';

especially handy if include_title is set to false so the title is not otherwise displayed

**Comment by billerickson** [comment]
Since Display Posts Shortcode uses the standard WordPress function, get_the_post_thumbnail(), it would be better to filter that to add titles if you want them. Ex: https://gist.github.com/billerickson/a07789f762d9858e82f475e56f803f44

Does that solve it for you?
