### ISSUE TITLE
Excerpt showing shortcodes present in the post content

### ISSUE THREAD

**Issue by diegocanal** [billerickson/display-posts-shortcode#113]
I attach a screenshot.  Is it the expected behavior?

![screen shot 2016-06-10 at 1310cest](https://cloud.githubusercontent.com/assets/3908213/15962630/c243c336-2f0c-11e6-8cb3-b4539f80ea10.png)

**Comment by billerickson** [comment]
Thanks for reporting this. You are correct, shortcodes should not appear in the custom excerpt. Please [download the latest version of the plugin](https://github.com/billerickson/display-posts-shortcode/archive/master.zip) and let me know if you still have issues.

**Comment by diegocanal** [comment]
Thanks for such a quick response. The issue has gone away, no more shortcodes in sight. Great plugin, thanks for sharing it.
