### ISSUE TITLE
When using include_title="false", set list-style to none on the li.

### ISSUE THREAD

**Issue by Nocturnaloner** [billerickson/display-posts-shortcode#117]
That's it, just noticed that the listing li elements have a visible bullet when the title is turned off.  Can't imagine most people would want that.

**Comment by billerickson** [comment]
Display Posts Shortcode provides no CSS styling. If you'd like to modify the styling you should make the changes to your theme's stylesheet. 

Alternatively, use `[display-posts wrapper="div"]` which makes the list items divs instead of list items.
