### ISSUE TITLE
Shortcodes are showing in excerpt

### ISSUE THREAD

**Issue by malavoie** [billerickson/display-posts-shortcode#121]
Posts containing shortcodes display the code in the excerpt text.

![screen shot 2016-07-23 at 2 56 17 pm](https://cloud.githubusercontent.com/assets/3386242/17079684/f3731984-50e5-11e6-9337-630af64884c6.png)

**Comment by diegocanal** [comment]
@malavoie I had the same problem and got a solution, please take a look at [#113](https://github.com/billerickson/display-posts-shortcode/issues/113)
