### ISSUE TITLE
Shortcodes don't work on start page

### ISSUE THREAD

**Issue by Dexxes** [billerickson/display-posts-shortcode#122]
Hey,

I'd like to put the latest post on my "static" start page, but the shortcode is only displayed as plain text.
Shortcodes of other plugins work there. I use the latest WP version.

Maybe I am doing something wrong, maybe it's a bug.

Regards, Julian

**Comment by billerickson** [comment]
Do you have the plugin installed and activated? What is the exact shortcode you are using?

**Comment by Dexxes** [comment]
Now it seems to work – i can’t tell why. I am sorry that I’ve bothered you.

 

Julian

 

Von: Bill Erickson [mailto:notifications@github.com] 
Gesendet: Freitag, 29. Juli 2016 08:11
An: billerickson/display-posts-shortcode <display-posts-shortcode@noreply.github.com>
Cc: Dexxes <jvb@live.de>; Author <author@noreply.github.com>
Betreff: Re: [billerickson/display-posts-shortcode] Shortcodes don't work on start page (#122)

 

Do you have the plugin installed and activated? What is the exact shortcode you are using?
