### ISSUE TITLE
disappearing of excerpt_more?

### ISSUE THREAD

**Issue by mclmclmcl** [billerickson/display-posts-shortcode#124]
After update Version **2.7.0** it seems like this parameter has gone:

Before:
![image](https://cloud.githubusercontent.com/assets/20777411/17301950/69448f2e-5822-11e6-89f8-e0baed2e3a50.png)

After:
![image](https://cloud.githubusercontent.com/assets/20777411/17302105/4db5f2e2-5823-11e6-9193-301b5fee3d33.png)

I used excerpt_more like this - 
excerpt_more="המשך »" 

Thank you
Michal

**Comment by billerickson** [comment]
Try adding this to your theme's functions.php file:

`add_filter( 'display_posts_shortcode_full_manual_excerpt', '__return_true' );`

In previous versions, if you provided a manual excerpt it would always display the full manual excerpt and append the excerpt_more to it, regardless of the excerpt's length.

Version 2.7.0 now truncates both manual excerpts and dynamically generated excerpts the same way - it limits the number of words to 55 (or whatever you set `excerpt_length` to). If the excerpt is shortened, the more text is added to the end. This ensures consistency of results regardless of your excerpt method.

But the filter I mentioned above returns the functionality back to how it was - manual excerpts display their full length followed by the more text.

See #123 for more information.

**Comment by mclmclmcl** [comment]
A thousand thanks for your quick response !

Michal
