### ISSUE TITLE
Use underscore instead of dash in shortcode name

### ISSUE THREAD

**Issue by whatsnewsisyphus** [billerickson/display-posts-shortcode#128]
Hello, the use of the dash in the shortcode throws all sorts of issues with other plugins and potential custom code that sees it as an invalid shortcode. Visual composer would be a chief example that most people would use.

"Shortcode names should be all lowercase and use all letters, but numbers and underscores should work fine too. Be wary of using hyphens (dashes), you'll be better off not using them. "
https://codex.wordpress.org/Shortcode_API

**Comment by billerickson** [comment]
I can't make the change you recommend in #129 as it is not backwards compatible. The 70,000+ current installations of this plugin would no longer work.

I can consider adding an additional shortcode, `[display_posts]` which can be used interchangeably with `[display-posts]`. 

Can you provide a specific example of where the latter shortcode would not work but the former would? I haven't received any reports of issues regarding this.

**Comment by whatsnewsisyphus** [comment]
If you use Visual Composer shortcode mapper, it will not accept it, and I'm sure many of those 70000 users do use VC. Basically, anytime you write [display-*] or [display], it will invoke your shortcode (if installed in the right order) even if the user meant some other thing like xml data in their html [display-list] for example. Adding an additional shortcode will help but still is affected by the bug. Better would be to make a find and replace on old databases and display a note on top for a couple versions to use display_list before deprecating the hyphen.

Using hyphens can create serious bugs where it creates clashes with other shortcodes that also start with [display, you can see [Wordpress's own warning.](https://codex.wordpress.org/Shortcode_API#Hyphens)

**Comment by whatsnewsisyphus** [comment]
The proper way to address backwards compatibility and fixes is to make primary the proper method and allow keeping the old method via settings for a while before people adopt the new one, potentially offering a search and replace through their database, not to ignore the issue. Well anyhow, it's just a heads-up because it is and will cause conflicts with many other shortcodes as pointed out in the official codex.
