### ISSUE TITLE
Ordering of posts

### ISSUE THREAD

**Issue by jeremywallis** [billerickson/display-posts-shortcode#130]
Hi,

I would like my posts to list in date order, with the most recent at the top of the list. No matter how I change DESC or ASC for the parameter 'order', it always lists the same, with the oldest post first.

The shortcode text I'm using is:
echo do_shortcode('[display-posts include_date="true" date_format="F j, Y" include_author="true" order="ASC" orderby="date" image_size="thumbnail" include_title="true" no_posts_message="Sorry, there are currently no posts." display-posts order="ASC" display-posts posts_per_page="10"]');

Any ideas?

Thanks.

**Comment by billerickson** [comment]
You've repeated `display-posts` and `order="ASC"` in the shortcode. I recommend changing it to:

```
echo do_shortcode('[display-posts include_date="true" date_format="F j, Y" include_author="true" order="ASC" orderby="date" image_size="thumbnail" include_title="true" no_posts_message="Sorry, there are currently no posts." posts_per_page="10"]');
```

But that shouldn't be causing the issue you are having. My guess is a plugin or your theme is modifying the query. I recommend switching to a default WordPress theme and disabling all plugins to determine the source.

**Comment by jeremywallis** [comment]
I removed the duplicates (evidence that I need to take a break …) and it works fine, many thanks for quick response.
