### ISSUE TITLE
Pull first image instead of featured image

### ISSUE THREAD

**Issue by phubner** [billerickson/display-posts-shortcode#134]
Not really an issue but something I might write and extension. I have a client who doesn't reliably use featured images and it would be handy to pull the first image of the post for the thumbnail. Do you think this would be something that I could add via an extension? Or would that be a change to this plugin directly?

**Comment by billerickson** [comment]
You could build it as an extension using the `display_posts_shortcode_output` filter. Check to see if `$image` is empty, and if it is then grab the first attached image and update the item's output.

Once #75 has been implemented it will be even easier as you won't have to re-assemble the output. 

[Here's how Genesis gets the first attached image.](https://gist.github.com/billerickson/c1cc27e6db199298b194a551d1cb1184)

**Comment by phubner** [comment]
Perfect! I'll look into that. I'll let you know the repo when I post it.
