### ISSUE TITLE
Pagination post list

### ISSUE THREAD

**Issue by kengzzzzz** [billerickson/display-posts-shortcode#135]
Help me : )
That's great plug-in but can I setup pagination of post list
Thank You

**Comment by billerickson** [comment]
[See the wiki](https://github.com/billerickson/display-posts-shortcode/wiki#pagination):

>A common question I receive is how to load the next page of results, or paginate the query. This plugin does not support pagination, nor will it in the future.

>If you need pagination in your query, you should not be using a shortcode. Use the WordPress core templates like the category archive or tag archive. Or if you must, build a [custom page template that overrides the main WordPress query](http://www.billerickson.net/code/pagination-in-a-custom-query/).
