### ISSUE TITLE
Shotcode not Working

### ISSUE THREAD

**Issue by ThunderbInazuma** [billerickson/display-posts-shortcode#138]
Hi. I've been using your plugin for maybe 6 months and it worked perfectly. However, today, I've received some messages from my followers, telling me that they found some strange words/code on the page where I use your plugin (https://pocketrotom.pt/pokedex/), as you can see on the image.

![image](https://cloud.githubusercontent.com/assets/22685810/23388554/c8e53784-fd5a-11e6-9505-3b4156a92fda.png)

I don't know what caused this, maybe a conflict with another plugin or with a script I posted on that page ( more probably the script, since I've inserted the shortcode on a clean page and it appears well, even though until now it appeared well.
The script in cause is:
<script>// <![CDATA[
function land(ref, target) { lowtarget=target.toLowerCase(); if (lowtarget=="_self") {window.location=loc;} else {if (lowtarget=="_top") {top.location=loc;} else {if (lowtarget=="_blank") {window.open(loc);} else {if (lowtarget=="_parent") {parent.location=loc;} else {parent.frames[target].location=loc;}; }}} } function jump(menu) { ref=menu.choice.options[menu.choice.selectedIndex].value; splitc=ref.lastIndexOf("*"); target=""; if (splitc!=-1) {loc=ref.substring(0,splitc); target=ref.substring(splitc+1,1000);} else {loc=ref; target="_self";}; if (ref != "") {land(loc,target);} }
// ]]&gt;</script>

Is there anyway to have the two of them keep working?

Thanks in advance

**Comment by billerickson** [comment]
I believe it is the script that is causing the issue. Instead of dropping the script directly in the page content, try creating a shortcode for it.

Add this to your theme's functions.php file:

```php

function be_script_shortcode() {
ob_start();
?>

// Place your script code here

<?php
$output = ob_get_clean();
return $output;
}
add_shortcode( 'be_script', 'be_script_shortcode' );
```

Then in the page content, you can place `[be_script]` where you'd like the script to be displayed.

**Comment by ThunderbInazuma** [comment]
Thanks. It worked!
