### ISSUE TITLE
Pass $atts instead of $original_atts in filters

### ISSUE THREAD

**Issue by MadSpaniard** [billerickson/display-posts-shortcode#145]
As an enhancement request, would it be possible to pass the $atts array instead of the $original_atts array in all of the filters, i.e. in the 'display_posts_shortcode_output' filter as well as the others?

Reason:  $original_atts only passes those attribute values that are explicitly specified in the shortcode, but will not pass any default attribute values (i.e. for attributes not explicitly specified in the shortcode) if you define any such default attribute values using the 'shortcode_atts_display-posts' filter.  

Since $original_atts is being passed by the filters, you can't get your hands on such default attribute values in callback functions you attach to the filters.

Thanks in advance for considering this enhancement.

**Comment by billerickson** [comment]
I believe you can access the $atts by using the filter `shortcode_atts_display-posts`. [See here](https://developer.wordpress.org/reference/hooks/shortcode_atts_shortcode/).

Can you provide an example of the specific instance you need this for?

I'm planning to [completely rebuild the output filter](https://github.com/billerickson/display-posts-shortcode/issues/75), and this is one more feature I should consider for that.

**Comment by MadSpaniard** [comment]
Hello Bill -

Yes, I looked into the 'shortcode_atts_display-posts' filter, and I use that to set new custom attributes and also define default values for attributes.

But I think the issue is that on line 36 the code says:  $original_atts = $atts;.  And then immediately after that, the code goes on to do the following:

// Pull in shortcode attributes and set defaults
$atts = shortcode_atts( array(
   <etc>
), $atts, 'display-posts' );

So any default values you set when you use the 'shortcode_atts_display-posts' filter happens AFTER the code assigns $original_atts = $atts; and since $original_atts is what is being passed in all subsequent filters, you will never receive those default values in the filter callback functions you define for those subsequent filters.

**Comment by billerickson** [comment]
I'll have to think about this. The reason we're passing $original_atts is so that custom attributes you add to the shortcode are available to the filters, rather than being stripped by `shortcode_atts()`.

Can you provide an example of how you're using this?

**Comment by MadSpaniard** [comment]
I'm not sure, but I believe shortcode_atts doesn't strip them, but rather augments:  meaning, if a particular attribute is not specified in the shortcode, then shortcode_atts will use the default value specified for it, else it will use whatever was specified in the shortcode.  I.e. the attributes and values specified in the shortcode have precedence over any defaults specified in 'shortcode_atts_display-posts'.

The case I'm using is I'm specifying a new attribute called "my_alignment" with a default value of "center".  I specify this using the 'shortcode_atts_display-posts' filter.  I do not explicitly set this new attribute in the shortcode unless I want a non-default alignment like my_alignment="left".  

So then in my callback function on the 'display_posts_shortcode_output' filter, I want to access the value for 'my_alignment', expecting to get the default value "center".  But I don't get that default value, because this attribute is not passed in via $original_atts because it was not explicitly specified in the shortcode.

If (for testing purposes only) I adjust the core plugin code on line 509 to pass in $atts instead of $original_atts, then it does work: I get the default value of 'center" when I access 'my_alignment in the callback.

Of course, the workaround is to put some validation code in my callback to effectively compute my default value via coding.  In essence, this way I'm "rolling my own attribute default code" rather than using the capabilities provided by ''shortcode_atts_display-posts'.

Thanks so much for your plugin, it's simply awesome.

**Comment by billerickson** [comment]
The `shortcode_atts()` function does a few things:
1. Specify a whitelist of attributes the shortcode supports
2. Provide default values for these attributes

You can modify the list of whitelisted attributes using the `shortcode_atts_display-posts`, as you have done. 

If I were to start over, I would have recommended this approach and built the plugin to use the `$atts` everywhere. But back when I first built this plugin, I didn't realize you could use that filter, and to resolve the issue of passing custom attributes I used `$original_atts` instead. 

Now many users are using this approach, and changing it now would break those sites (including many sites that I built). 

Here's a rough example: 
```
/**
 * Testing custom attributes
 *
 */
function ea_testing_custom_attributes( $output, $original_atts ) {
	if( !empty( $original_atts['custom_attr'] ) )
		$output .= '<strong>' . esc_html( $original_atts['custom_attr'] ) . '</strong>';
	return $output;
}
add_filter( 'display_posts_shortcode_output', 'ea_testing_custom_attributes', 10, 2 );
```

If you then use `[display-posts custom_attr="foo"]` . If we pass the `$original_atts`, this works. If we pass the `$atts` this doesn't work.
