### ISSUE TITLE
Add new filter 'display_posts_shortcode_title_class'

### ISSUE THREAD

**Issue by MadSpaniard** [billerickson/display-posts-shortcode#146]
Currently there is no filter to adjust the class that gets applied to the shortcode 'title':  the class is hard-coded as 'class="display-posts-title"' with no way to adjust it. 

How about adding a new 'apply_filters()' on line 547 to enable the title class to be adjusted?  For example, a typical case may be to change the class to "widget-title" instead of "display-posts-title".

The workaround I've been using is to not use the 'title' attribute at all in the shortcode, instead specify my own attribute 'my_title' and use the 'display_posts_shortcode_wrapper_open' filter with something like this in the callback function:

$my_title = sanitize_text_field( $atts['my_title'] );
if ( ! empty( $my_title ) )
    $wrapper_open = $wrapper_open . '<h4' . ' class="widgettitle widget-title">' . $my_title . '</h4>';
return $wrapper_open;

**Comment by billerickson** [comment]
This is what the output filter is for:


```php
/**
 * Display Posts Shortcode - change title class 
 *
 */
function be_dps_change_title_class( $output, $original_atts, $image, $title ) {
  return str_replace( $title, '<h4 class="widgettitle widget-title">' . get_the_title() . '</h4>', $output );
}
add_filter( 'display_posts_shortcode_output', 'be_dps_change_title_class', 10, 4 );
```

It should be easier to make modifications of each "output part" (like the title) once the output filter has been rebuilt (#75)

**Comment by MadSpaniard** [comment]
Bill -

I'm not sure your suggestion will work:  I'm talking about the OVERALL title, not the INDIVIDUAL POST title, i.e. the class for the 'title' attribute, not the class for the individual post item.  

The 'display_posts_shortcode_output' filter applies to the "inner" output, i.e. the output for a single post item.  I'm referring to the 'outer' part, i.e. what happens between lines 521..533 in the code.

**Comment by MadSpaniard** [comment]
Bill -

Actually, regarding my earlier coment, I menat to say what happens between lines 521 and 550 (not 521..533).

Thanks so much for all of your help, the plugin is awesome.
