### ISSUE TITLE
Post per page set to "4" not working

### ISSUE THREAD

**Issue by sylvainbotter** [billerickson/display-posts-shortcode#148]
Hello,

Thank you for this amazing plugin! I love it!

I have some very small issues of customisation (see --> http://www.lytchee.com/chine/)

1) I set "4" for "posts_per_page", but it shows me 10? How to fix that?
2) How to remove bullets points?
3) how to put spacing between post? (vertically) 

**Shortcode:** 

[display-posts tag=“video” posts_per_page=“4” include_excerpt="true" excerpt_length="20" image_size="medium" excerpt_more="Read more" columns="2" excerpt_more_link="true"]

thank you for your kind support!

Sylvain

**Comment by billerickson** [comment]
It sounds like your theme or a plugin is modifying the query, changing the number of posts shown per page. I recommend you temporarily change your theme and disable plugins to identify the issue.

For questions 2 and 3, you'll need to make CSS modifications. These can be done in Appearance > Customize > Custom CSS, or by directly editing your theme's stylesheet. You'll want to add something like this:

```
.display-posts-listing li {
list-style-type: none;
padding-bottom: 20px;
}
```

**Comment by sylvainbotter** [comment]
Hello,

Thanks for amazing support! 

;)

Have a nice afternoon,

Sylvain
