### ISSUE TITLE
Doesn't work on multiple WPML translated Pages

### ISSUE THREAD

**Issue by LoadstarHater** [billerickson/display-posts-shortcode#151]
So this is my home site in German:
https://canbuy.ch
As you can see Blog Posts are displayed.
Code:
<h2>Blog/News</h2>
[display-posts image_size="thumbnail" posts_per_page="5" wrapper="div"  ]

And this is the same site in Englisch:
https://canbuy.ch/en
As you can see nothing is displayed but the code is exactly the same:
<h2>When bored</h2>
[display-posts image_size="thumbnail" posts_per_page="5" wrapper="div"  ]

Any idea what's the problem?

**Comment by billerickson** [comment]
I recommend you forward this request to WPML. I have no experience with that plugin, but they test to confirm compatibility and resolve any issues. See: https://wpml.org/plugin/display-posts-shortcode/
