### ISSUE TITLE
Showing date before title

### ISSUE THREAD

**Issue by kuzmandi** [billerickson/display-posts-shortcode#152]
How can I show the date before (instead of after) the title?

When I use `[display-posts include_date="true" date_format="d.m.Y"]` it looks like this:

`Title A 2017-05-16`
`Title B 2017-05-17`
`Title C 2017-05-18`

What I want is this (e.g.):

`2017-05-16: Title A`
`2017-05-17: Title B`
`2017-05-18: Title C`

Are there any formatting possibilities for delimiters?

**Comment by antonyjsmith** [comment]
Example is here: [https://github.com/billerickson/display-posts-shortcode/issues/127](url)

**Comment by billerickson** [comment]
As mentioned above, you can change the order and content of the output using the output filter.
