### ISSUE TITLE
Add feature to exclude posts by ID

### ISSUE THREAD

**Issue by kanejamison** [billerickson/display-posts-shortcode#154]
I would love a default parameter to be exclude a specific post ID.

Here's the use example I'm working with, where I'm listing all children except for a specific ID.

[display-posts post_parent="1340" order="ASC" orderby="title" post_type="page" posts_per_page="50" **exclude="1389"**]

Thanks for your time & work on this plugin - I have found it greatly helpful numerous times and just contributed a donation.

**Comment by billerickson** [comment]
I've just added an `exclude` parameter. You can either specify one post ID or a comma-separated list of multiple IDs. 

There is already a parameter for excluding the current post: `[display-posts exclude_current="true"]`.
