### ISSUE TITLE
only outputs list of 5 most recent

### ISSUE THREAD

**Issue by Tanmccuin** [billerickson/display-posts-shortcode#155]
I recently demo'd this on one of my client sites and regardless of the ID passed, the shortcode always only outputs a list of the 5 most recent post titles w/ links. I can pass a function to set the defaults, which works to show excerpt / images etc. but every ID i pass is ignored in favor of 5 most recent posts. Curious if this plugin has been tested with PHP7?

**Comment by billerickson** [comment]
It sounds like your theme or a plugin is affecting the query. I recommend you switch to the default theme and disable all plugins, then enable them one-by-one to determine where the issue is.

Yes, the plugin works with PHP7.
