### ISSUE TITLE
Customizing link display (title and meta field)

### ISSUE THREAD

**Issue by thnk2wn** [billerickson/display-posts-shortcode#157]
I'm trying to use this to generate a "series index / outline" when I have several blog posts that are all linked as a part of the same series. I'm able to query and get the list I want with the titles. 

However each post has a title like "Subject Matter - Part 1" but the actual "series subject / header" is something more specific. For example "Git Command Line - Part 1" as post title and "Branching and Merging" as the subject which I store in a custom meta field. So what I'd really like for each list item is something like "{title} - {meta-series-subject}". 

I'm not sure what this would look like but if the item content could be templatized maybe something like the following.

> [display-posts wrapper="ol" wrapper_class="my-class" meta_key="meta-series" meta_value="meta-series-name" display_format="{title} - {meta-series-subject}" orderby="series_index" order="ASC" post_status="any"]

**Comment by billerickson** [comment]
While not currently built into the plugin, you can accomplish this by using the `display_posts_shortcode_output` filter ([example](https://www.billerickson.net/code/add-time-to-display-posts-shortcode/)).

The second parameter is `$atts`, which are the original shortcode attributes. Look for your custom attribute (ex: display_format), and if it's not empty then modify the output as needed.

**Comment by thnk2wn** [comment]
Thank you @billerickson. Forgive me but I've not dealt with WP filters before - how do I got about setting this up / configuring it for use?

**Comment by billerickson** [comment]
You should place this code either in your theme's functions.php file, or a [Core Functionality](https://www.billerickson.net/core-functionality-plugin/ plugin.

This is just an example and is untested.

```php
/**
 * DPS Template 
 *
**/
function ea_dps_template( $output, $atts, $image, $title, $date, $excerpt, $inner_wrapper, $content, $class ) {

	// Only run if we’ve provided a format
	if( !isset( $atts['display_format'] ) )
		return $output;

	$output = str_replace( 
		array(
			{title},
			{meta-series-subject}
		),
		array(
			get_the_title(),
			get_post_meta( get_the_ID(), ‘series_subject’, true)
		),
		$atts[‘display_format’]
	);

	// Add wrapping elements
	$output = ‘<‘ . $inner_wrapper . ‘” class=“’ . implode( ‘ ‘, $class ) . ‘”>’ . $output . ‘</‘ . $inner_wrapper . ‘>’;

	return $output;

}
add_filter( 'display_posts_shortcode_output', 'ea_dps_template', 10, 9 );
