### ISSUE TITLE
The plugin does not support Chinese directory names?

### ISSUE THREAD

**Issue by bittyboy** [billerickson/display-posts-shortcode#160]
The plugin does not support Chinese directory names?How do I use the catalog ID to show the article?

thank you~!

**Comment by billerickson** [comment]
I'm not sure what you mean by it not supporting directory names. Can you provide an example and, if possible, a pull request with your requested change to the plugin?

What is a catalog ID? Do you mean category ID? `[display_posts category_id="123"]`
