### ISSUE TITLE
Content word wrap is breaking words

### ISSUE THREAD

**Issue by cybergenx** [billerickson/display-posts-shortcode#161]
The plugin is great.  The issue we are having is that the content is breaking words.  Parameters we are using are: 
[catlist content=full numberposts=15 orderby=title order=asc name="Teams"

Example below:
The first place team was called the Titans.  They had several home runs but were not able to acco
mplish anything else.

As you can see the break is incorrect.

Any help would be greatly appreciated.  Thank you!

**Comment by billerickson** [comment]
That is not a shortcode provided by this plugin. The only shortcode this plugin creates is `[display-posts]`.

**Comment by cybergenx** [comment]
Thanks.  Sorry for the error. 

Can you tell me if your plugin has the ability to display the entire contents of all posts belonging to the same category on a page?  The posts are book recommendations and don't snippets that require clicking on a more link to the full post.  They are at best 5 sentences and a link.

**Comment by billerickson** [comment]
[display-posts category="book-recommendations" posts_per_page="999" include_content="true"]
