### ISSUE TITLE
Can't display both categories and post tags after title

### ISSUE THREAD

**Issue by pokyah** [billerickson/display-posts-shortcode#162]
Hi Bill and all the developers, thanks for this great plugin ! 

I've got some problem to make both the post categories **AND** tags appear after the post title. Here is my shortcode : 

`[display-posts post_tag_display="true" category_display="true" category_label="|" include_title="true" include_link="TRUE" posts_per_page="10000"]`

While using it, I only get the categories.

How should I adapt it to achieve what I expect : catgories **AND** tags?

Thanks for your support

**Comment by billerickson** [comment]
There is no parameter for `post_tag_display`.  The `category_display` accepts the name of the taxonomy you want to display. Ex:

[display-posts category_display="true"] - displays the categories
[display-posts category_display="category"] - displays the categories.
[display-posts category_display="post_tag"] - displays the tags

If you want to display both categories and tags, you'll need to customize the output of the plugin using the `display_posts_shortcode_output` filter. See some examples of customizations here: https://www.billerickson.net/code-tag/display-posts-shortcode/

**Comment by pokyah** [comment]
Thanks for your answer Bill. 

Could you provide me a short step by step explanation about how to achieve this customization ?
I don't really see how to create such a combination and  where to add it in my WP installation. 

Thanks for your support

**Comment by billerickson** [comment]
Add something like this to your theme's functions.php file or a [Core Functionality plugin](https://www.billerickson.net/core-functionality-plugin/): https://gist.github.com/billerickson/ae379e9b4af1eb16e037cc7a1b6516c9

Then in your post, add `[display-posts category_display="true"]`. By default that would display only the categories attached to this post, but with the modification above it will also include the tag listing.

**Comment by pokyah** [comment]
Thank you so much @billerickson  ! Your support is very appreciated. Thanks for taking some of your time to help me. It works perfectly now.
