### ISSUE TITLE
Posts starting_with

### ISSUE THREAD

**Issue by henrimeijer** [billerickson/display-posts-shortcode#163]
Hi,
First of all awesome plugin, great job! I now have this running: 

`[display-posts category="XXX" include_title="true" order="ASC" orderby="title" posts_per_page="1000"]`

I would like to add `title starting_with="a"` - So from the category "XXX" it will only show posts with title starting with "A"

Cheers,
Henri

**Comment by billerickson** [comment]
Unfortunately there is no way to query for posts based on the first letter (review the available [WordPress Query arguments here](https://codex.wordpress.org/Class_Reference/WP_Query)). 

I recommend you write custom code that hooks on `save_post` that saves the post's first letter as post meta, then you can do a meta query like [display-posts meta_key="be_first_letter" meta_value="a"]
