### ISSUE TITLE
Exclude pages?

### ISSUE THREAD

**Issue by mariusrudolph** [billerickson/display-posts-shortcode#164]
Hi, is it possible to exlude pages? I currently use the post_parent parameter to include child pages. I would like to exclude some of them.

**Comment by billerickson** [comment]
Yes, you can use the `exclude` parameter. From the [documentation](https://github.com/billerickson/display-posts-shortcode):

> **exclude** Specify one or more post IDs to exclude from query
Default: false
Example: [display-posts exclude="9, 11"]

**Comment by mariusrudolph** [comment]
Hi Bill, thanks! I tried that with the following code 

`[display-posts post_type="page" post_parent="current" wrapper="div" wrapper_class="container" posts_per_page="500" image_size="thumbnail" order="DESC" exclude="5090, 4758, 4706, 5090, 4774, 4767, 5098"]`

But those pages still show up. Any clue why?

**Comment by billerickson** [comment]
Try removing the spaces. Ex: 2,5,9...

**Comment by mariusrudolph** [comment]
Hi, nope - thumbnails still show up in that list. Just to make sure I am doing it right. Those IDs are the IDs of the pages I would like to exclude, correct?

Any idea how to debug or fix it?

**Comment by antonyjsmith** [comment]
I'm having the same issue

**Comment by antonyjsmith** [comment]
Scratch that, updated to the latest version from Github [2.8.1] and all good. The wordpress repo version [2.8.0] doesn't include the... err.... exclude feature ;P
