### ISSUE TITLE
Works with limits on WP.com

### ISSUE THREAD

**Issue by thehrisworld** [billerickson/display-posts-shortcode#169]
Not really an issue but a heads up.
Have not seen this elsewhere and not sure if anyone knows. 
Had to move a WP site from '.org' to '.com' and the following format works in the '.com' platform.

`[display-posts category="{category-slug}"]`

Lists cleanly and limits to 10 - better than nothing considering the '.com' site is on the free account.

Example can be seen here with two categories listed
[https://thehrisworld.wordpress.com/2017/06/05/education-inspiration-business/](https://thehrisworld.wordpress.com/2017/06/05/education-inspiration-business/)

**Comment by billerickson** [comment]
Yes, this plugin comes pre-installed on all WordPress.com accounts. You should be able to use all parameters, although if they aren't running the latest version of the plugin there could be a few that aren't on WordPress.com yet.
