### ISSUE TITLE
Visual Composer posts are losing their layout and images when put through display-posts

### ISSUE THREAD

**Issue by xenopuff** [billerickson/display-posts-shortcode#170]
![screen shot 2017-09-16 at 18 45 29](https://user-images.githubusercontent.com/5756358/30514565-4b377a1a-9b0f-11e7-8eab-858b3c2358ea.png)
![screen shot 2017-09-16 at 18 45 45](https://user-images.githubusercontent.com/5756358/30514566-4b39773e-9b0f-11e7-81b4-c85d7829d06b.png)

Hiya,
I love this plugin - but it's not doing what I want it to right now.
So I've made one blog post in visual composer for each and every advent calendar this year (don't ask). I want to show all of them on one page, as a list showing the entirety of each post, but display-posts isn't taking pictures/expanding areas/counters etc through.

I was just making it in one page before, but my computer was running **so** slowly. I thought this might be easier. I was gravely mistaken.

Hope this is the right place for this. 
Please help! :'(

**Comment by billerickson** [comment]
When you use the include_content parameter, the shortcode will display the full content of that post, but the plugin provides no styling of this - it's up to your theme (and any relevant plugins) to do this.

I'm guessing that your theme has a unique template for the single post (`single.php`) that displays the content the way you want. But when you use this plugin, it does not use that `single.php` file to put together the page.

**Comment by xenopuff** [comment]
Ok, any tips on fixing it?

**Comment by billerickson** [comment]
Ask whoever built it to make it work.  They'll likely need to build a custom shortcode for outputting it in the custom format you require.
