### ISSUE TITLE
Displays error message on front end when no featured image is present in custom post type

### ISSUE THREAD

**Issue by Mugane** [billerickson/display-posts-shortcode#171]
Please remedy this ASAP. Cannot update this plugin until this is fixed since errors are displayed on public assets:

**Problem:**
Custom post type with featured image. If no featured image is uploaded, shortcode produces **"has_post_thumbnail returned false"** error which it displayed in plain text on the front end.

**Solution:**
Please add setup_postdata( $post ); after line 388 in display-posts-shortcode.php (version 2.8.0). See https://wordpress.stackexchange.com/questions/18856/featured-image-vs-post-thumbnail-has-post-thumbnail-lies to learn why this is necessary.

**Comment by billerickson** [comment]
On [line 404](https://github.com/billerickson/display-posts-shortcode/blob/master/display-posts-shortcode.php#L404), we run `$listing->the_post();` . The `the_post()` method calls `setup_postdata()`.

I've tested and confirmed there are no issues. I added this shortcode to a page: `[display-posts image_size="true"]` . A few of the posts had images, a few didn't, and there were no issues on the page.
