### ISSUE TITLE
the plugin dosn't load a Html from the post

### ISSUE THREAD

**Issue by d00nn1** [billerickson/display-posts-shortcode#172]
the problem is how can i load the html like ifream from youtube for example or like this HTML at the plugin  from shortcode 

<div class='post embed-container'><iframe height='480' width='854' src='https://www.youtube.com/embed/hT_nvWreIhg?enablejsapi=1&modestbranding=1&playsinline=1&rel=0&color=white' frameborder='0' allowfullscreen></iframe></div>

is posible to change som code to load  text and html  in post when thet posible is was whery nice?

**Comment by billerickson** [comment]
If you use `[display-posts include_content="true"]` it will display the full content of the post, including whatever iframes you have inserted in it.

**Comment by d00nn1** [comment]
th a lot you creat a great plugin and thets work fine thx a lot have nice day
