### ISSUE TITLE
Setting up a default image

### ISSUE THREAD

**Issue by kmalmal** [billerickson/display-posts-shortcode#173]
Any help adding a shortcode filter for displaying a default thumbnail image is much appreciated.

ie:[display-posts category_id="11,12,13" posts_per_page="4" image_size="thumbnail" _default_image "true"_  include_date="true"]

**Comment by billerickson** [comment]
Here you go: https://gist.github.com/billerickson/420446dd1810f00a4210178b5bbbad9e

Add that to your theme's functions.php file.  Then update your shortcode to be:

`:[display-posts category_id="11,12,13" posts_per_page="4" image_size="thumbnail" default_image="123" include_date="true"]`

Where "123" is the ID for the image you'd like to use as the default.
