### ISSUE TITLE
Order By and Custom Field

### ISSUE THREAD

**Issue by matthieugd** [billerickson/display-posts-shortcode#175]
Hello,

I use the shortcode to display a list of custom type posts ordered by the value of a custom field. I also filter by a custom taxonomy and a value for it.

Here's the call 

`[display-posts taxonomy="etiquette_xxx" tax_term="hybrides" post_type="mycustomtype" order="ASC" meta_key="ranking_hybrides" orderby="meta_value_num" include_content="true" image_size="medium" wrapper="div" wrapper_class="xyz"]`

The `ranking_hybrides` is a custom field (using the ACF plugin). The strange thing is I got posts with no value for this custom field appearing at the top. I'm not sure how can I exclude those fields.

**Comment by billerickson** [comment]
Take a look at the actual metadata associated with those posts, either using the Custom Fields metabox or in single.php adding `print_r( get_post_meta( get_the_ID() ) );`

My guess is ACF is actually saving a meta_key for those fields and leaving the value blank, so they DO have that meta key. 

I recommend using the `display_posts_shortcode_args` filter to check to see if `!empty( $args['meta_key'] ) && 'ranking_hybrides' == $args['meta_key']`, and if true then add a meta_query:

```
$args['meta_query'] = array(
	array(
		'key' => 'ranking_hybrides',
		'value' => ' ',
		'compare' => '!='
	)
);
```

**Comment by matthieugd** [comment]
Yes indeed I looked at the wp_meta table in the database for those posts and they have an entry for the customer field. I did the filter_args trick and it worked, thank you. I saw a meta_compare option when searching for a solution. Is that something you look at to add ?

**Comment by billerickson** [comment]
The plugin doesn't currently support meta queries (ie the `meta_query` parameter in WP_Query). If/when support for that is added, the meta_compare will be included too. It will probably work similarly to tax_queries in the plugin: https://github.com/billerickson/display-posts-shortcode/wiki#multiple-taxonomy-queries

I haven't built that yet because the simpler `meta_key` and `meta_value` parameters work just fine in 99% of cases.

**Comment by billerickson** [comment]
But for forwards compatibility, when filtering the args you should first check for the parameter.

```
$meta_query= array(
	array(
		'key' => 'ranking_hybrides',
		'value' => ' ',
		'compare' => '!='
	)
);
if( ! empty( $args['meta_query'] ) )
	$args['meta_query'] = array_merge( $args['meta_query'], $meta_query );
else
	$args['meta_query'] = $meta_query;
```
