### ISSUE TITLE
Move title inside display-posts-listing tag

### ISSUE THREAD

**Issue by andy-sdc** [billerickson/display-posts-shortcode#176]
To format the output to match other items on our website I have had to move the display-posts-title <h2> tag inside the display-posts-listing <div> tag I am using.  I couldn't find a way to achieve this using extra options on the [display-posts] shortcode and so have modified the .php file as per the attached patch.

Is there a way this can be achieved using the standard version of the plugin or a cleaner version incorporated into the next version?

-Andy
[move-header.txt](https://github.com/billerickson/display-posts-shortcode/files/1478011/move-header.txt)

**Comment by billerickson** [comment]
Unfortunately no, I will not be moving the title in future versions as this would negatively affect users currently using the title. 

I recommend you don't use the `title` attribute, but instead add a custom attribute like `title_before_output`. Then use the `display_posts_shortcode_wrapper_open` filter to add the title. Example: `[display-posts title_before_output="My Title"]`

Code: https://gist.github.com/billerickson/ce1310e03adf410fff4b24eb87a94a02
