### ISSUE TITLE
Display Comments

### ISSUE THREAD

**Issue by robblackheart** [billerickson/display-posts-shortcode#178]
Very useful plugin, kudos. 
The ability to display comments for each post would be a good addition, will you be adding this?

**Comment by billerickson** [comment]
Unfortunately no, I do not plan on adding a feature to display comments on the posts. 

I think the best approach would be to [specify your own template part](https://github.com/billerickson/display-posts-shortcode/wiki#using-template-parts), then include the comments inside that partial.
