### ISSUE TITLE
nested display posts

### ISSUE THREAD

**Issue by rosea1** [billerickson/display-posts-shortcode#181]
IF you display a post on a page which within that post content itself also has a display post tag then it doesn't display the nested post.

**Comment by billerickson** [comment]
This is by design. You could end up with infinite loops, where Post A has a shortcode that shows the full content of Post B, and Post B has a shortcode that displays the full content of Post A.

**Comment by rosea1** [comment]
So is there no way that i can achieve this ?

**Comment by billerickson** [comment]
Correct, there is no way to recursively call this shortcode (display a post's content which contains the shortcode).

**Comment by rosea1** [comment]
Interesting. This could potentially be a future enhancement? The code could intelligently determine if a post has already been displayed and throw an error if it has instead of infinite looping. 

Anyway thanks for the info!

**Comment by billerickson** [comment]
No, this will not be added as a future enhancement.

If you'd like, you can fork the plugin and remove [this line](https://github.com/billerickson/display-posts-shortcode/blob/master/display-posts-shortcode.php#L472), which adds the code that disables the `[display-posts]` shortcode inside of posts being listed.
