### ISSUE TITLE
terms must be separated with a comma AND a space after the comma...

### ISSUE THREAD

**Issue by smeric** [billerickson/display-posts-shortcode#183]
hi,

in the wiki you write that :
>"tax_(count)_term
>Which terms to include (if more than one, **separate with commas**)
>Default: empty"

but on line 340 you do :
`$terms = explode( ', ', sanitize_text_field( $original_atts['tax_' . $count . '_term'] ) );`

and there is **a space** in the delimiter string ! so... I was unable to make my tax query work until I found that ;)

thanks for this nice plugin by the way :)

**Comment by airdrummer** [comment]
unfortunately that's a common "feature" in wp:-\ the post-by-email function also requires ', ' for [category cat1, cat2, etc]

**Comment by smeric** [comment]
well, sure :)

but maybe it could be wise to do instead, for example :
`$terms = array_map( 'trim', explode( ',', sanitize_text_field( $original_atts['tax_' . $count . '_term'] ) ) );`
so it may work with and without white spaces ?

or to give an example in the wiki for people to see they need the whitespaces without having to scan the source code ?

what do you think ?

**Comment by billerickson** [comment]
This has been fixed in 2.9.1. You can now either use a comma or comma-space to separate items in the following parameters:
- post_type
- id
- exclude
- post_status
- tax_term
