### ISSUE TITLE
Improvements on category display filters

### ISSUE THREAD

**Issue by rubengc** [billerickson/display-posts-shortcode#185]
When category are displayed there is no way to customize it properly because this filter just pass the final output:

```
/**
/**
* Filter the list of categories attached to the current post.
*
* @since 2.4.2
*
* @param string   $category_display Current Category Display text
*/
$category_display_text = apply_filters( 'display_posts_shortcode_category_display', $category_display_text );
```

If you are looking to rebuild the output or change anything, you can't know which taxonomy has passed, so a recommended arguments could be:

```
/**
* Filter the list of categories attached to the current post.
*
* @since 2.4.2
*
* @param string   $category_display_text 	Current Category Display text
* @param array    $terms 					Terms Listed
* @param string   $category_display 		Terms Taxonomy
* @param array    $atts 					Shortcode attributes
*/
$category_display_text = apply_filters( 'display_posts_shortcode_category_display', $category_display_text, $terms, $category_display, $atts );
```

Other improvements to this section will be the ability to filter the term output (for example to add classes based on term slug and a new parameter like `category_sep` to let override the term output implode

**Comment by billerickson** [comment]
That's a great idea. I'll include this in the next release.
