### ISSUE TITLE
Using post titles for ALT tags

### ISSUE THREAD

**Issue by waybis** [billerickson/display-posts-shortcode#187]
I've noticed your plugin uses the media library ALT tag if one is specified for a post feature image, and leaves it blank if no ALT tag.  I was wondering whether you would consider changing this or adding a parameter to use the relevant post title instead, for a future release? 

I imagine there are many websites that are displaying blank ALT tags, so it might even be worth using the post title as a default rather than the media library.

Looking at use of ALT tags by themes in archive pages it seems to be common practise to use the post title instead of the media library for the ALT tag.  Although this does seems to contravene the intended use of ALT tags, perhaps navigational thumbnails are an exception.

Google does seem to use ALT tags to understand the context of a link to another page from an image, like it uses anchor text in a text link, so there should be value in avoiding blank ALT tags and making them relevant to the linked post.

**Comment by billerickson** [comment]
This plugin uses `get_the_post_thumbnail()`, a standard WordPress function, for generating images. To add or modify the alt tag, you'll need to filter the output of this function. 

Display Posts Shortcode is not specifying the alt tags for the image, so it's not a filterable option inside this plugin.

**Comment by waybis** [comment]
Thanks for the reply and pointing me in the right direction, very helpful, this seemed to do the trick: [https://mekshq.com/change-image-alt-tag-in-wordpress/](https://mekshq.com/change-image-alt-tag-in-wordpress/)
