### ISSUE TITLE
Thumbnail not showing

### ISSUE THREAD

**Issue by moalisa** [billerickson/display-posts-shortcode#188]
Hi,

I am currently developing a webpage for a restaurant/hotel.

I have tried using the shortcode so that the featured images are being displayed, however I have had no luck so far. This is the code I have been using so far: 
[display-posts category=”krog” include_excerpt="true" display-posts image_size="thumbnail"]

I would also like, if possible, to get some help writing the shortcode so that the list could look somewhat like this:

**Comment by moalisa** [comment]
I forgot to mention that the website url is dev.smakrike.se and I would like the posts to show up as they do on this page: http://dev.smakrike.se/category/krog/

**Comment by billerickson** [comment]
Are you sure the featured images are specified for those posts/pages? 

Also, you should change your shortcode to this: 

`[display-posts category=”krog” include_excerpt="true" image_size="thumbnail"]`

(remove the `display-posts` before `image_size`)

There are two ways you can make the shortcode output match your site:
1. Use CSS to style the shortcode output similarly to your site
2. Use a[template part](https://github.com/billerickson/display-posts-shortcode/wiki#using-template-parts) to replace the shortcode's output with code from your theme.
