### ISSUE TITLE
Addition of <article> (HTML element)  option  to the wrapper parameter

### ISSUE THREAD

**Issue by diegocanal** [billerickson/display-posts-shortcode#190]
Hi,
The `<article>` HTML element is the most appropriate markup for posts lists –from a structural semantics point of view–. I believe it should be added as an option (in addition to the `<ul>`, `<ol>` and `<div>` options) for the _wrapper_ parameter.

**Comment by billerickson** [comment]
Wouldn't it make more sense for the wrapper to be `<section>` and the individual posts to be `<article>`?

**Comment by diegocanal** [comment]
That is precisely what I meant, `<article>` for individual posts, sorry I wasn't clear enough.

The actual wrapper (for the listings) could be `<section>` but I wouldn't force the use of it. In fact it could also be `<div>` or even no wrapper at all. Perhaps it is time to add a new parameter "individual_post_wrapper".

I think the perfect solution would be having both parameters ("wrapper" and "individual_post_wrapper") and allowing the user to choose any HTML element for both of them. Even a no-wrapper option for the (listings) "wrapper" would be very useful for those that do no need it.

**Comment by diegocanal** [comment]
Any news on this Bill?

**Comment by diegocanal** [comment]
Right, I had missed the `display_posts_shortcode_output` filter, that's good!

On the other hand, I don't think using `<section>` as the outer wrapper is the best option. It may apply to some scenarios but it is not the most common one nor is specifically recommended by any of the specifications ([HTML Living Standard](https://html.spec.whatwg.org/multipage/sections.html#the-section-element), [HTML 5.1](https://www.w3.org/TR/html51/sections.html#the-section-element) or [HTML5](https://www.w3.org/TR/html50/sections.html#the-section-element)) they all state that:

> Each section should be identified, typically by including a heading (h1-h6 element) as a child of the section element.

Which won't be the case. 

On top of that let's imagine we want to use the shortcode several times on the same page, for example, to group lists of posts by categories. If we had a `<section>` element wrapping each group, we would end up having several sections which may not apply to the structural semantics we are pursuing.

I believe that the essential markup we really need is the `<article>` element for the inner wrapper. Using `<section>` for the outer seems to me too (semantically) strong, and too reductionist, a simpler `<div>` element for the outer would be more flexible and adequate in my opinion. In the end, the person who really wants a `<section>` outer wrapper can easily add it by hand when inserting the shortcode.

**Comment by billerickson** [comment]
I'm closing this issue as it will be addressed in DPS 3.0, which is a complete rebuild as a Gutenberg block.
