### ISSUE TITLE
The ability to show read more link always

### ISSUE THREAD

**Issue by besabestin** [billerickson/display-posts-shortcode#197]
I wish we are able to show the read more link whether the excerpt is fully or partially shown. Currently if there is enough space to show the whole excerpt the read more link is avoided.

**Comment by TravisRothlisberger** [comment]
You can manually tweak display-posts-shortcode.php:909 to make this **always** work. Change:
`$excerpt = wp_trim_words( strip_shortcodes( $post->post_excerpt ), $length, $more );`
to
`$excerpt = wp_trim_words( strip_shortcodes( $post->post_excerpt ), $length) . $more;`

I would think this should be the default when excerpt_more_link = true.

**Comment by billerickson** [comment]
I've updated the default behavior to always display the excerpt_more text.
