### ISSUE TITLE
[Extension Review] Display Posts Shortcode - Pinch Zoomer

### ISSUE THREAD

**Issue by shazahm1** [billerickson/display-posts-shortcode#199]
An extension for the Display Posts Shortcode plugin which adds support pinch zooming post images on mobile devices and mouse wheel zooming on desktops.

https://github.com/shazahm1/Display-Posts-Shortcode-Pinch-Zoomer

**Comment by billerickson** [comment]
Looks great! I've added it to the list of [Extension Plugins](https://github.com/billerickson/display-posts-shortcode/wiki#extension-plugins)
