### ISSUE TITLE
Having custom taxonomies injected into the DPS li class

### ISSUE THREAD

**Issue by DamonNomadJr** [billerickson/display-posts-shortcode#200]
I don't know if this question was brought up before but I am doing a simple js that uses classes to detect specific blocks with specific taxonomies. On DPS however, it does not include the taxonomies in the class of that post by default as WordPress does. Is there any way I can add that feature?

**Comment by billerickson** [comment]
By default the only class added is 'listing-item', but you can use the `display_posts_shortcode_post_class` filter to add any classes you like.

If you'd like to add all the classes WordPress typically puts on post listings, use `get_post_class()`. Example (code goes in functions.php or a [core functionality plugin](https://www.billerickson.net/core-functionality-plugin/)):

```php
/**
 * Display Posts Shortcode, post classes 
 *
 */
function be_dps_post_classes( $classes ) {
	return get_post_class( $classes );
}
add_filter( 'display_posts_shortcode_post_class', 'be_dps_post_classes' );
```
