### ISSUE TITLE
excerpt dash as attribute

### ISSUE THREAD

**Issue by GitHub-Mike** [billerickson/display-posts-shortcode#204]
You can please add an attribute for the excerpt dash? This is not always needed and restricts formatting.

`'excerpt_dash'  => false,`

```
$excerpt_dash = ( $excerpt_dash ) ? ' <span class="excerpt-dash">-</span>' : '';
$excerpt = $excerpt_dash . ' <span class="excerpt">' . $excerpt . '</span>';
```

**Comment by billerickson** [comment]
You can now disable it with `[display-posts include_excerpt="true" include_excerpt_dash="false"]`

**Comment by GitHub-Mike** [comment]
Thanks for implementing my suggestion!

**Comment by waybis** [comment]
I only just noticed the space appears to be missing in front of the excerpt dash on the front end, and looks like it was introduced with this change $excerpt = '<span class="excerpt">' . $excerpt . '</span>';
