### ISSUE TITLE
Set a class on excerpt_more text

### ISSUE THREAD

**Issue by TravisRothlisberger** [billerickson/display-posts-shortcode#205]
For example, `<span class="excerpt-more">`

**Comment by billerickson** [comment]
Version 3.0 of Display Posts Shortcode will introduce new theming options and include additional classes on elements like this. 

For now, you can implement this with the following code in your functions.php file: https://gist.github.com/billerickson/ef7a392654121251a1b16481d5190f1b

**Comment by billerickson** [comment]
Actually, now that I re-read the issue I see you're referring to the more text, not the entire excerpt. Sorry about that.

I just added an `.excerpt-more` class to the more text. It's either a `<span>` or an `<a>` depending on whether `excerpt_more_link = true`
