### ISSUE TITLE
Issue with tags/categories on Pages

### ISSUE THREAD

**Issue by skyfoxdesign** [billerickson/display-posts-shortcode#206]
This plugin only seems to work with categories/tags on posts, rather than pages, even though categories/tags can be added to pages. This potentially spreads to custom post types too, but I;ve yet to test.

**Comment by billerickson** [comment]
Have you tried specifying the post type in your shortcode? 

The default post type is "post" but you can set it to "page" or any other custom post type. You can even set it to all post types. Ex:

`[display-posts post_type="any" category="news"]`

If you're still having issues, make sure the taxonomy is correct. You may have a "Page Categories" taxonomy that is different from the core "Categories" taxonomy. You can query for custom taxonomies:

`[display-posts post_type="any" taxonomy="page_category" tax_term="news"]`

**Comment by skyfoxdesign** [comment]
I have indeed tried using the post_type correctly.

`post_type="page"` combines with `tag="tag_slug"` results in... no results. Despite multiple pages tagged with the correct tag.

**Comment by billerickson** [comment]
I just tested and am not having this issue.

On a clean WordPress install:
1. Installed Display Posts Shortcode
2. Installed [Tag Pages](http://wordpress.org/plugins/tag-pages)
3. Edited a page, adding a tag of "testing"
4. On a separate page I added `[display-posts post_type="page" tag="testing"]`
5. The first page appeared in the listing ([screenshot](https://cl.ly/35ff4394d95e))

It sounds like you have another plugin that's modifying or somehow affecting queries in WordPress.

I recommend you install the [Health Check](https://wordpress.org/plugins/health-check/) plugin, then go to Dashboard > Health Check > Troubleshooting > Enable Troubleshooting Mode.

This will disable all plugins *only for you* (all other visitors to the site will be unaffected). I also recommend you switch to a default theme (again, only affects you).

Go to Plugins and click "Enable with troubleshooting" under Display Posts Shortcode ([screenshot](https://cl.ly/e0b1a189ed75)). Go back to your page and see if it's working. If it is, you can enable plugins one-by-one to see which one is causing the conflict.

**Comment by billerickson** [comment]
Your WordPress.org support forum post had more information on the situation. Here's the answer to your problem: https://wordpress.org/support/topic/strange-error-display-pages-not-posts/#post-11053514

**Comment by skyfoxdesign** [comment]
Thanks for your help so far - still an issue arises regarding parent/child pages. Parents show fine, but children don't show at all, even when using `post_type="any"`

**Comment by billerickson** [comment]
I think I found the issue (see above). Can you try re-downloading the plugin from GitHub and seeing if this resolves it?

Thanks

**Comment by skyfoxdesign** [comment]
Solved! You're a star, thank you.

**Comment by billerickson** [comment]
No, thank **you** for catching that. You saved me from a lot of support messages when this goes live on Monday :)
