### ISSUE TITLE
Pagination Extension

### ISSUE THREAD

**Issue by billerickson** [billerickson/display-posts-shortcode#209]
[Some users](https://wordpress.org/support/topic/post-navigation-14/) have requested pagination - previous / next links to navigate through the listings.

While I don't believe this belongs in the core plugin, it would make a nice extension.

**Comment by GitHub-Mike** [comment]
Hello Bill,

thanks for awesome plugin.

What's the status here? Is there a concrete schedule for this feature?

**Comment by billerickson** [comment]
There is no concrete schedule. I work on this plugin around my actual client work, so I'll work on it next time I have some free time.

Here's a few issues that will need to be addressed by this extension:

1. Ensure it doesn't conflict with WP core pagination on archives and singular content.
2. Ensure multiple shortcodes on the same page can be paginated separately. Every shortcode will need a unique URL parameter for its pagination.
3. While it would be preferable to use [rewrite endpoints](https://codex.wordpress.org/Rewrite_API/add_rewrite_endpoint) for the pagination so they could be cached, the same shortcode could be used in multiple contexts (home / archive / single post / page...) and rewrite endpoints could complicate rewrite rules and lead to 404s.
4. It might be worth using AJAX for loading new posts without reloading the page

**Comment by billerickson** [comment]
Here is the first draft of the pagination extension: [Display Posts - Pagination](https://github.com/billerickson/Display-Posts-Pagination). 

In the top right corner, click “Clone or Download”, then “Download zip”. Once installed and activated, you can enable pagination for your listing using `[display-posts pagination="true"]`

![screenshot](https://dvfr2lc5dhzsq.cloudfront.net/items/2J1N3u2t3v1l242w2p3t/Screen%20Shot%202019-03-13%20at%206.05.02%20PM.png)

**Comment by GitHub-Mike** [comment]
Hello Bill,

thanks for the quick implementation! But why are you using another plugin? I don't think that's so good.

It also works for me with multiple shortcodes on the same page.

One more request. Can you please make the position of the navigation configurable. Outside the listing is unfavorable for me. Could you solve that with a additional custom key in the args array?

**Comment by billerickson** [comment]
Pagination does not belong in the core plugin, so this will remain an extension.

I've added an option to display pagination inside the listing: `[display-posts pagination="true" pagination_inside="true"]` . Download the latest version of the plugin to get this feature.

I **do not** recommend using this option if the results are listed as an unordered list or ordered list as it is improper HTML markup to include a non-list-item inside the ul/ol.

**Comment by DwaipayanDe** [comment]
Hi Bill,

I have the latest version of the display posts plugin (3.0.2) . I tried using both the below shortcodes -

[display-posts category="westbengal" order="ASC" pagination="true" pagination_inside="true"]

[display-posts category="westbengal" order="ASC" pagination="true" ]

But unfortunately, there was no pagination observed. Is the pagination implemented in plugin yet? am i missing something?

**Comment by billerickson** [comment]
The pagination extension is a separate plugin. You need to install [Display Posts Pagination](https://github.com/billerickson/Display-Posts-Pagination) in addition to Display Posts for pagination to work.

**Comment by DwaipayanDe** [comment]
Hi Bill..sorry for bugging you..may be this is a silly question..but i could not find this plugin 'Display Posts Pagination' searching for it in the wordpress plugin serach dashboard. Is this plugin available in wordpress?

**Comment by billerickson** [comment]
It's not available on WordPress.org. You can download it here: https://github.com/billerickson/Display-Posts-Pagination/archive/master.zip

Then on your site go to Plugins > Add New > Upload and upload the zip file.

**Comment by DwaipayanDe** [comment]
Ok..Thanks..But this link is giving me an error. Providing the screenshot as well..

![image](https://user-images.githubusercontent.com/64208428/80109938-c1702a00-859b-11ea-817e-4b5913246967.png)

**Comment by billerickson** [comment]
That's strange. Try going here ([Display Posts Pagination](https://github.com/billerickson/Display-Posts-Pagination)), click the Green "Clone or Download" button in the top right, then click Download Zip. That's where I copied the URL from.

**Comment by DwaipayanDe** [comment]
Ok..i managed to download it just now..may it was a mistake from my end. Thanks a lot for your help. I shall upload this and then use the shortcode [display-posts category="westbengal" order="ASC" pagination="true" ]. I guess thats all that is needed, isnt it? Thanks again.

**Comment by billerickson** [comment]
Correct, this plugin adds the pagination="true" parameter to the shortcode.

**Comment by NidhinAS** [comment]
How increase the size of 'Next' button in pagination

**Comment by NidhinAS** [comment]
Please send me a solution to increase the font size of next and previous button in pagination..it seems very small font...

**Comment by billerickson** [comment]
Display Posts does not include any styling - that is handled by your theme. You will need to add CSS to your theme (or in Appearance > Customize > Additional CSS) to alter the styling of the pagination.

**Comment by NidhinAS** [comment]
ok.thank you for your reply

**Comment by terminalbe** [comment]
Hello... is there any way to paginate using ajax so the webpage does not need to reload. Please see the following page. When I click on the pages, the entire page reloads, and I have to click on the correct tab (Publications) again. Thank you in advance. https://www.cmbg3.com/shareholders/john-gardella

**Comment by billerickson** [comment]
Unfortunately no, the pagination addon does not use AJAX. You could hire a developer to modify the plugin to use JavaScript to load the results inline, but that is not a feature I plan to add.

**Comment by huynhkimberly** [comment]
Thank you so much for making this plugin and extensions. Honestly amazing and so flexible. Wish I was as skilled as you! X)

**Comment by DanDawson** [comment]
I just really wanted to thank you for creating the [Display-Posts-Pagination](https://github.com/billerickson/Display-Posts-Pagination) plugin. I was able to easily install it and it is working great for my needs, making my site much more usable as the number of posts grows on my site. Thanks!
