### ISSUE TITLE
Nested display posts include duplicate results

### ISSUE THREAD

**Issue by mattys101** [billerickson/display-posts-shortcode#212]
I have been using the `display_posts_shortcode_inception_override` filter for a while now to allow nested uses of the display posts shortcode but it appears that the recent 3.0 update has broken the capability. It appears that the results of the nested query get included into the results of original query leading to duplicated output. I suspect this is a result of making the `$dps_listing` query object global?

Is this something that you are able to fix as I find this feature very useful? Or do you plan on deprecating this functionality? I note that in another issue (#181) you indicated that it is not possible to have nested uses at all.

**Comment by billerickson** [comment]
Have you tried [excluding duplicate posts](https://displayposts.com/2019/01/03/exclude-posts-already-displayed/)?
