### ISSUE TITLE
Little upgrade

### ISSUE THREAD

**Issue by YaL11** [billerickson/display-posts-shortcode#218]
Hi

I have to use a lot of time the same some code so i add a hook

```
function be_display_posts_shortcode( $atts ) {
	// Original Attributes, for filters
    $original_atts = $atts;

    //Hook, default attributes
    if(isset($atts['defaults'])){
        $atts = apply_filters('display_posts_shortcode_default_'.$atts['defaults'], $atts);
    }```

then use it
````
add_filter( 'display_posts_shortcode_default_dps_defaults', 'dps_defaults' , 10, 2 );
````
````
function dbs_defaults(){
return array(
                'layout'                => "my-layout",
                'ignore_sticky_posts'   => true,
                'order'                 => "DESC",
                'orderby'               => 'date',     
                'post_type'             => 'post',
                'posts_per_page'        => '3',
                'title'                 => "Recent Posts",
                'wrapper'               => "div",
                'wrapper_class'         => "my-class",
                
            );
}
````

so i can use the shortcode [display-post default="dps_defaults"]

**Comment by billerickson** [comment]
You can already accomplish this using the `shortcode_atts_display-posts` filter. See here: https://displayposts.com/2019/01/04/change-default-attributes/
