### ISSUE TITLE
When using [display-posts taxonomy=...] twice on a page, only the first shortcode is rendered

### ISSUE THREAD

**Issue by davidatbu** [billerickson/display-posts-shortcode#222]
When I use `[display-posts ..]` more than once in a page, only the first instance renders if the second instance uses taxonomy parameters.

If I remove the first instance, the second instance renders perfectly. If I remove parameters having to do with taxonomies from the second instance, both render perfectly.

For the record, here are the shortcodes I am using, with the names of people changed for privacy reasons.
```html
[display-posts taxonomy=content-type tax_term=project  taxonomy_2=investigator tax_2_term=john-doe]
<p> Some html ...... </p>
[display-posts taxonomy=content-type tax_term=publication  wrapper=ol content_class=aligncenter include_title=false include_content=true taxonomy_2=investigator tax_2_term=john-doe]
```

**Comment by billerickson** [comment]
You need to wrap the shortcode settings in quotes for the shortcode to work. Try using this instead:

```
[display-posts taxonomy="content-type" tax_term="project"  taxonomy_2="investigator" tax_2_term="john-doe"]
<p> Some html ...... </p>
[display-posts taxonomy="content-type" tax_term="publication"  wrapper="ol" content_class="aligncenter" include_title="false" include_content="true" taxonomy_2="investigator" tax_2_term="john-doe"]
```

**Comment by davidatbu** [comment]
Hi @billerickson , I appreciate very much the support! 

I tried out wrapping the shortcode settings in quotes. But that is apparently not the issue, because it still doesn't work.

Even more interestingly, **putting down the exact same shortcode settings twice** works perfectly fine! This makes me think that this is more related to how the query is being constructed. To demonstrate, both **A** and **B** work just fine, but **C**(the original example) doesn't work.
## A
```
[display-posts taxonomy="content-type" tax_term="project"  taxonomy_2="investigator" tax_2_term="john-doe"]
<p> Some html ...... </p>
[display-posts taxonomy="content-type" tax_term="project"  taxonomy_2="investigator" tax_2_term="john-doe"]
```
## B
```
[display-posts taxonomy="content-type" tax_term="publication"  wrapper="ol" content_class="aligncenter" include_title="false" include_content="true" taxonomy_2="investigator" tax_2_term="john-doe"]
<p> Some html ...... </p>
[display-posts taxonomy="content-type" tax_term="publication"  wrapper="ol" content_class="aligncenter" include_title="false" include_content="true" taxonomy_2="investigator" tax_2_term="john-doe"]
```
## C
```
[display-posts taxonomy="content-type" tax_term="project"  taxonomy_2="investigator" tax_2_term="john-doe"]
<p> Some html ...... </p>
[display-posts taxonomy="content-type" tax_term="publication"  wrapper="ol" content_class="aligncenter" include_title="false" include_content="true" taxonomy_2="investigator" tax_2_term="john-doe"]
```

**Comment by billerickson** [comment]
That's really strange. It sounds like something may be interfering with the queries.

I recommend you try the Health Check plugin so you can view the page with only Display Posts active for your user. More information: https://displayposts.com/2019/04/20/using-health-check-plugin-to-find-theme-and-plugin-conflicts/

**Comment by davidatbu** [comment]
Thanks again @billerickson . The issue is, I'm working on a Multisite platform with limited access to one site. This means I cannot install any plugins.
The only way I can see myself debugging further is to spin up a Wordpress installation of my own, install DPS, install a taxonomy plugin, add some taxonomies, and try to recreate the scenario above.

**Comment by davidatbu** [comment]
You were right. On a clean install of wordpress and a custom type/taxonomy plugin, using DPS twice on a page works just fine. If anything, I'll take it up with IT. Thanks!
