### ISSUE TITLE
Just display post count?

### ISSUE THREAD

**Issue by gingerbeardman** [billerickson/display-posts-shortcode#223]
Is it possible to just show a count of the posts that match the shortcode?

I've read the docs and nothing jumps out at me regarding how to do this.

**Comment by billerickson** [comment]
Here's a detailed guide on how to display the post count with the shortcode: https://displayposts.com/2019/08/14/display-post-count-as-title-of-listing/

**Comment by gingerbeardman** [comment]
Over and above, Bill! Many thanks.
