### ISSUE TITLE
Change of behavior in 2.9.1

### ISSUE THREAD

**Issue by gzohop** [billerickson/display-posts-shortcode#236]
There is change in behavior in commit:

https://github.com/billerickson/display-posts-shortcode/commit/2564e417bcba0aa6f89e8c12e9f9e971130ba32a

I'm using code:

[display-posts post_type="page" post_parent="13" layout="landing" orderby="menu_order" order="ASC" wrapper="div" wrapper_id="landing_content" include_link="false"]

Before this commit i get 4 pages on list that have parent with id 13, but with that commit i get the four pages and all the children on list.
I've tried excluding children pages with post_parent__not_in, but it does nothing.

The only thing I've found to work so far is to comment out:

 https://github.com/billerickson/display-posts-shortcode/blob/6fe3defc7bfdadbddbc652289a6e11acbde94d71/display-posts-shortcode.php#L471

How can I limit the list just to those four pages or maybe it can be fixed by some other way than making dps_listings not global?

**Comment by billerickson** [comment]
I don't see how making the query a globally accessible variable would affect the query results. Do you have any code that is modifying display posts or the $dps_listing variable that might be conflicting with it?

Do you happen to have a staging site available? I'd love to hop in and debug the issue on your site without affecting your live website.

**Comment by gzohop** [comment]
> I don't see how making the query a globally accessible variable would affect the query results. Do you have any code that is modifying display posts or the $dps_listing variable that might be conflicting with it?

That's weird for me to.
I have not found any references to $dps_listing, I have tried even renaming it
 but it does not change behavior.
> 
> Do you happen to have a staging site available? I'd love to hop in and debug the issue on your site without affecting your live website.

What kind of access would you need, shell access to the OS, because it might be problematic :/
Can you give me some ideas where to start debuging, I suspect that id has to be problem with custom theme that site uses?

**Comment by billerickson** [comment]
I'd start by looking at the query arguments to see what is passed to WP_Query. Something like this should work (don't add this to the live site because the debugging code will be visible to everyone):

```
add_filter( 'display_posts_shortcode_args', function( $args, $atts ) {
	ea_pp( $args, 'Arguments' );
	ea_pp( $atts, 'Attributes );
	return $args;
}, 10, 2 );

/**
 * Pretty Printing
 *
 * @since 1.0.0
 * @author Chris Bratlien
 * @param mixed $obj
 * @param string $label
 * @return null
 */
function ea_pp( $obj, $label = '' ) {
	$data = json_encode( print_r( $obj,true ) );
	?>
	<style type="text/css">
		#bsdLogger {
		position: fixed;
		top: 0;
		right: 0px;
		border-left: 4px solid #bbb;
		padding: 6px;
		background: white;
		color: #444;
		z-index: 999;
		font-size: 1.25em;
		width: 400px;
		height: 100vh;
		overflow: scroll;
		}

		.admin-bar #bsdLogger {
			top: 32px;
			height: calc( 100vh - 32px );
		}
	</style>
	<script type="text/javascript">
		var doStuff = function(){
			var obj = <?php echo $data; ?>;
			var logger = document.getElementById('bsdLogger');
			if (!logger) {
				logger = document.createElement('div');
				logger.id = 'bsdLogger';
				document.body.appendChild(logger);
			}
			////console.log(obj);
			var pre = document.createElement('pre');
			var h2 = document.createElement('h2');
			pre.innerHTML = obj;
			h2.innerHTML = '<?php echo addslashes($label); ?>';
			logger.appendChild(h2);
			logger.appendChild(pre);
		};
		window.addEventListener ("DOMContentLoaded", doStuff, false);
	</script>
	<?php
}
```

I'd then comment out the global variable and run that code again to see if there's any change to the query arguments.
