### ISSUE TITLE
Feature suggestion: add query parameter is_featured for Woocommerce featured products

### ISSUE THREAD

**Issue by diegocanal** [billerickson/display-posts-shortcode#237]
In case you are open to adding this query parameter, please take into account that [since Woocommerce 3, you need to use a Tax Query as featured products are now handled by product_visibility custom taxonomy for the term "featured"](https://stackoverflow.com/a/46247028/6643916).

**Comment by billerickson** [comment]
You can already query for WooCommerce featured posts using a tax query: `[display-posts post_type="product" taxonomy="product_visibility" tax_term="featured"]`

Here's [more information on taxonomy queries in Display Posts](https://displayposts.com/2019/01/07/taxonomy-queries/).

You could also [create a shortcut argument](https://www.billerickson.net/shortcut-args-for-display-posts-shortcode/) on your site so `[display-posts featured_product="true"]` accomplished the same query as the above shortcode without having to remember all of the attributes.

**Comment by diegocanal** [comment]
Awesome Bill. Thank you!
