### ISSUE TITLE
What are the steps to add an extension ?

### ISSUE THREAD

**Issue by johnchristopher** [billerickson/display-posts-shortcode#238]
I haven't seen the procedure in the doc. Should the file just be dropped in `wp-content/plugins/display-posts` or are they plugins that should live in `wp-content/plugins/alpha-view` (and need display-posts to be installed) ?

**Comment by billerickson** [comment]
Sorry if it isn't clear. The extensions are separate plugins that extend the functionality of Display Posts.  You can install them in the same manner you install any other plugin.

You can go to Plugins > Add New > Upload and upload the zip file of the plugin, or if you're comfortable with SFTP you can drop the extension plugin directory inside /wp-content/plugins/ . 

Once the files have been uploaded, go to the main Plugins screen in WordPress and activate the extension plugin.

**Comment by johnchristopher** [comment]
Thanks, that clears things up for me.
