### ISSUE TITLE
Optimizing the query even further

### ISSUE THREAD

**Issue by alinademi** [billerickson/display-posts-shortcode#239]
Hi Bill
Wondering if it is possible to do this on DPS and if this idea is even valid?

“ when the wp_post table contains thousands of rows, the query execution could take seconds.
When we don’t need pagination, we should ever set no_found_rows to true, making the query run dramatically faster.
“
Excerpt from
[This article explains it](https://kinsta.com/blog/wp-query/) 

I have tested the SQL statement and found the difference but not as dramatically as the article describes.

“Removing `SQLr_CALC_FOUND_ROWS` setting `no_found_rows` to false”

I really would like to see the result of this on DPS.
What filter should I use to test this? And maybe how...

Happy holidays!

**Comment by billerickson** [comment]
You can use the `display_posts_shortcode_args` filter to customize the arguments passed to WP_Query. 

Try adding this to your functions.php file:

```
/**
 * Display Posts - No Found Rows
 *
 * @param array $args Args.
*/
function be_dps_no_found_rows( $args ) {
	$args['no_found_rows'] = true;
	return $args;
}
add_filter( 'display_posts_shortcode_args', 'be_dps_no_found_rows' );
```
