### ISSUE TITLE
post archiving

### ISSUE THREAD

**Issue by JenniferSuess** [billerickson/display-posts-shortcode#243]
I'd like have a date field on which a post should appear in a different list, such as an archive date. It needs to be a specific date, NOT a certain number of days from the published or modified date. I was thinking of storing this is a custom field. I don't see anything I can use in the date_query_column options that would allow me to do this. Any ideas? I'm doing this in WordPress.

**Comment by billerickson** [comment]
If it's stored as a custom field, you can use a [meta query](https://displayposts.com/2019/03/27/meta-queries/) with the `meta_key` and `meta_value` properties.

**Comment by JenniferSuess** [comment]
Thanks I’ll try that.

**Comment by JenniferSuess** [comment]
I added a custom field, and tried using meta_compare=">" (although I don't see this in the documentation you referenced). It doesn't work. Is it supported? Any hints?

**Comment by billerickson** [comment]
Unfortunately no, the plugin does not yet support the meta_compare parameter, but with a bit of code you could add support for that parameter on your site. Something like this (untested):

```
/**
 * Display Posts, meta compare
 */
function be_dps_meta_compare( $args, $atts ) {
	if ( ! empty( $atts['meta_compare'] ) {
		$args['meta_compare'] = $atts['meta_compare'];
	}
	return $args;
}
add_filter( 'display_posts_shortcode_args', 'be_dps_meta_compare', 10, 2 );
```
