### ISSUE TITLE
DPS not adding posts to $_genesis_displayed_ids in widget area

### ISSUE THREAD

**Issue by MadSpaniard** [billerickson/display-posts-shortcode#244]
Hello - I'm using DPS in several Genesis sites (Infinity Pro, Altitude Pro).  

It seems that if I invoke DPS from a text widget in a widget area (e.g. Front Page 1-7), the desired post(s) are properly displayed in that widget area, but the post IDs are not added to the global $_genesis_displayed_ids.

However, if I use the old "Genesis Sandbox Featured Content Widget" plugin in those same Front Page 1-7 widget areas to display the same desired posts, then the post IDs are also added to $_genesis_displayed_ids.

Shouldn't DPS add posts to $_genesis_displayed_ids by default?  (I'm hoping this is the case, as there's further processing I'd like to do on those posts, which depends on being able to use $_genesis_displayed_ids.

Hopefully there's a simple trick I'm missing to get DPS to add posts to $_genesis_displayed_ids.  Any ideas?

Thank you in advance for your help.

**Comment by billerickson** [comment]
Display Posts doesn't have built-in support for theme-specific features like this, but you can use the filters to make it work.

Add this to your theme's functions.php file or a [core functionality plugin](https://www.billerickson.net/core-functionality-plugin/): https://gist.github.com/billerickson/44005c4d78f5a532c9c1f3d9bb8d8321

**Comment by MadSpaniard** [comment]
Thank you Bill!  Your suggestion worked perfectly, and $_genesis_displayed_ids is now successfully populating with the IDs.  

Thank you again.  Cheers.
