### ISSUE TITLE
pagination not displayed when offset parameter is uset

### ISSUE THREAD

**Issue by shelbypereira** [billerickson/display-posts-shortcode#245]
I tested multiple times and was able to reproduce on my website that offset="0" was working but when I set offset to "1"  it failed (pagination was not being displayed).

Actually offset="1" is important since often we want to display the whole first article and then links to the next N articles.

**Comment by billerickson** [comment]
Pagination in WordPress doesn't work if you use offset, so the Display Posts Pagination plugin only works if you leave the offset parameter blank.
