### ISSUE TITLE
Pass the shortcode attributes as an argument in the "display_posts_shortcode_wrapper_open" filter

### ISSUE THREAD

**Issue by amfriedman** [billerickson/display-posts-shortcode#65]
This is an enhancement proposal. I want to render all the shortcode attributes as class names for the outer HTML wrapping of the plugin's output. If the display_posts_shortcode_wrapper_open filter had a second argument that passed the instance's attributes into this function, then this could be accomplished. Without such contextual awareness, this filter isn't so useful besides changing out the tag name.

**Comment by billerickson** [comment]
That filter already includes the attributes as a second parameter.
