### ISSUE TITLE
Sticky posts

### ISSUE THREAD

**Issue by TheChief79** [billerickson/display-posts-shortcode#86]
How can i display just sticky posts? Couldn't find an option.

Maybe somthing like this:

[display-posts post_status="sticky"]

**Comment by billerickson** [comment]
This plugin doesn't currently support sticky posts. You could use the built-in filters to add another query argument, something like [display-posts sticky="true"]. Here's a tutorial: http://www.billerickson.net/shortcut-args-for-display-posts-shortcode/
