### ISSUE TITLE
Add support for "current" author

### ISSUE THREAD

**Issue by billerickson** [billerickson/display-posts-shortcode#95]
[display-posts author="current"]

If the current user is logged in, it will lists posts by that user.

What should it display if a non-logged-in user is viewing the page? Should it show no posts, or list all posts (not limited to an author)?

See: https://wordpress.org/support/topic/display-current-author-instead-of-specific-one?replies=2#post-7361223

**Comment by kodeine** [comment]
@billerickson 
Any updates on this?

**Comment by billerickson** [comment]
You can download the latest version of the plugin here: https://github.com/billerickson/display-posts-shortcode/archive/master.zip

I'm going to wait to push this out on WordPress.org until I have a few more features I can include in this version.

**Comment by prasadkal** [comment]
[display-posts author="current"] is not working. Wordpress version 4.4.2. 
Also I want particular author must show for particular post is it possible  in this plugin? Posts have categories.
