### ISSUE TITLE
Suggestion regarding current page slug

### ISSUE THREAD

**Issue by davshirley** [billerickson/display-posts-shortcode#96]
Is there, a way to do something like tag="current-page-slug"?  That way, I could embed all the posts that are tagged with the same slug-as the page that I am on...

example:
you have a bunch of pages that are bios for a team of people. The page slug for these pages are each person's name:  "john-r-jones", "devlin-mcnull" etc.

You also have a bunch of posts that reference these people.  if john-r-jones is tagged in some posts you can easily pull up a list of posts tagged for john on his bio page and posts for devlin on his bio page using the exact same shortcode.

**Comment by billerickson** [comment]
Out of the box, no. But you can create a shortcut argument for it yourself. Here's a tutorial: http://www.billerickson.net/shortcut-args-for-display-posts-shortcode/
