### ISSUE TITLE
Undefined Index's

### ISSUE THREAD

**Issue by graph-io** [billerickson/display-posts-shortcode#99]
Hi Bill,
Love this thing. I have a non serious issue but none the less am trying to learn and can't figure out how to qwell this notice I'm receiving. I'm customizing in my functions.php to display an icon based on the value of a custom field. I'll post the code below but essentially every one of the if statements in it cause the notice to appear and (when debug is enabled) only display the notice and no results. I have tried adding an !isset into the code but cant seem to get it correct. Would you mind lending a hand?
------------------------------------------------------------
function be_display_posts_classes( $output, $atts, $image, $title, $date, $excerpt, $inner_wrapper) {
	
	global $post;
	
	$classes = 'listing-item';
	
	// Counter
	global $dps_counter;
	$classes .= ' dps-list-item-' . $dps_counter;
	$dps_counter++;
	
	// Current Page
	global $dps_current_page;
	if( $dps_current_page == get_permalink() )
		$classes .= ' current';
		
>>>>CAUSING NOTICE>>		$classes .= $atts['post_type'];
		
		$categories = (array) get_the_category();
    $separator = " ";
    $thelist = '';
    foreach($categories as $category) {    // concate
        $thelist .= $separator . $category->category_nicename;
    }
	
>>>>CAUSING NOTICE>>	if ( $atts['include_excerpt'] )
		// Now let's rebuild the excerpt with the read more link at the end
		{
                //Now we can truncate
			$read_more ='<p><a href="'.get_permalink() . '"> Read More...</a></p>';
		$excerpt = '<div class="excerpt"><p>' . substr(get_the_excerpt(), 0,285 ) . '...</p></div><div class="post-footer"><a class="uprepbtn" href="'. get_permalink() .'">Read More</a></div> <hr>';
		}
	else $excerpt = '';
		
		$pdf = esc_attr( get_post_meta( $post->ID, 'pdflink', true ) );
		$sig = esc_attr( get_post_meta( $post->ID, 'author', true ) );
	
>>>>CAUSING NOTICE>>	if ( $atts['include_date'] ) $date = ' <div class="header"><h3>'  . $title . '<span class="date">'. get_the_date('M j, Y') .' | <a class="PDF Link Title" href="' . $pdf . '" title="PDF Link" target="_blank"><i class="fa fa-file-pdf-o"></i></a></span></h3><div class="signature">' . $sig . '</div></div>';
	else $date = '';
	
>>>>CAUSING NOTICE>>	if ( $atts['include_content'] ) $content = ' <div class="content">' . get_the_content() . '</div>';
	else $content = '';
	
	$thetitle = $title;
	
	$title = $thetitle;

	// Now let's rebuild the output.
	$output = '<' . $inner_wrapper . ' class="' . $classes . ' ' . $thelist . '  ' . get_post_format() . '">' . $date . $title . $excerpt . $content . $image . '</' . $inner_wrapper . '>';

	// Finally we'll return the modified output
	return $output;
	
}
add_filter( 'display_posts_shortcode_output', 'be_display_posts_classes', 10, 7 );

Help is much appreciated!

**Comment by billerickson** [comment]
I'm sorry, I can't really read what's going on there. Can you paste the full, functioning code as Gist ( http://gist.github.com ) and paste a link?

**Comment by billerickson** [comment]
Now I see it in the other post: https://gist.github.com/graph-io/866c2fb94890c4a683d5#file-function-be_display_posts_classes-txt

**Comment by billerickson** [comment]
Try this: https://gist.github.com/billerickson/5c605cc9aaad8032cc16

And here's a diff comparing it to your file: https://www.diffchecker.com/3mx8zcfo

**Comment by graph-io** [comment]
Thanks, worked like a charm and that litte Diff tool is super helpful. You're impressively fast on here!
